name: Node-js-App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: npm test

      # - name: Debug workspace
      #   run: |
      #     pwd
      #     ls -la

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t app .

          docker tag app:latest $DOCKER_USERNAME/nodejsapp:latest

          

          echo "Pushing Docker image..."


          docker push $DOCKER_USERNAME/nodejsapp:latest
